# Generated by Django 5.0.1 on 2024-02-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0005_alter_college_college_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='tution',
            new_name='tuition',
        ),
    ]
