# Generated by Django 5.0.1 on 2024-01-26 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0002_college_department_program_courseunit_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default='2022-12-12', null=True)),
                ('time_slot', models.CharField(choices=[('8am-11am', '8am to 11am'), ('9am-12pm', '9am to 12pm'), ('1pm-4pm', '1pm to 4pm'), ('2pm-5pm', '2pm to 5pm'), ('5pm-7pm', '5pm to 7pm')], max_length=20)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_three.courseunit')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_three.program')),
                ('venue_or_room', models.ManyToManyField(to='app_three.room')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
            },
        ),
    ]
