# Generated by Django 5.0.1 on 2024-01-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0003_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='venue_or_room',
            field=models.ManyToManyField(blank=True, to='app_three.room'),
        ),
    ]
