# Generated by Django 5.0.1 on 2024-01-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0003_timetable'),
        ('app_two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_three.program'),
        ),
    ]
