# Generated by Django 5.0.1 on 2024-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0004_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fingerprint_characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
