# Generated by Django 5.0.1 on 2024-02-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0005_student_fingerprint_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fingerprint_encoding',
        ),
    ]
