# Generated by Django 5.0.1 on 2024-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0007_remove_student_fingerprint_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fingerprint_encoding',
        ),
        migrations.AddField(
            model_name='student',
            name='fingerprint_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
