# Generated by Django 5.0.1 on 2024-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0009_alter_student_fingerprint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fingerprint_location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
