# Generated by Django 5.0.1 on 2024-02-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0013_alter_student_fingerprint_xtics1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='paid_tution',
            new_name='paid_tuition',
        ),
    ]
