# Generated by Django 5.0.1 on 2024-02-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0006_rename_tution_program_tuition'),
        ('app_two', '0014_rename_paid_tution_student_paid_tuition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='timetable',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='course_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_three.courseunit'),
        ),
    ]
