# Generated by Django 5.0.1 on 2024-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0003_timetable'),
        ('app_two', '0002_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid_tution',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_course_units',
            field=models.ManyToManyField(blank=True, to='app_three.courseunit'),
        ),
    ]
