# Generated by Django 5.0.1 on 2024-01-26 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('college_name', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('program_name', models.CharField(max_length=50, null=True, unique=True)),
                ('tution', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_three.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=50, null=True)),
                ('taught_in', models.CharField(blank=True, choices=[('Year 1 Sem 1', 'Year 1 Sem 1'), ('Year 1 Sem 2', 'Year 1 Sem 2'), ('Year 2 Sem 1', 'Year 2 Sem 1'), ('Year 2 Sem 2', 'Year 2 Sem 2'), ('Year 3 Sem 1', 'Year 3 Sem 1'), ('Year 3 Sem 2', 'Year 3 Sem 2'), ('Year 4 Sem 1', 'Year 4 Sem 1'), ('Year 4 Sem 2', 'Year 4 Sem 2'), ('Year 5 Sem 1', 'Year 5 Sem 1'), ('Year 5 Sem 2', 'Year 5 Sem 2')], max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_three.program')),
            ],
            options={
                'verbose_name': 'Course Unit',
                'verbose_name_plural': 'Course Units',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(max_length=50, null=True, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_three.college')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_three.school'),
        ),
    ]
