# Generated by Django 5.0.1 on 2024-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0006_remove_student_fingerprint_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fingerprint_characteristics',
        ),
        migrations.AddField(
            model_name='student',
            name='fingerprint_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
