# Generated by Django 5.0.1 on 2024-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0012_remove_student_fingerprint_encoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fingerprint_xtics1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fingerprint_xtics2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
