# Generated by Django 5.0.4 on 2024-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0018_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
