# Generated by Django 5.0.4 on 2024-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0019_alter_student_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fingerprint_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
